# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c48c46644176a0005e982827fc46fa1ca80b7e33237bf114484001163e89845077272e35968a8df223f692b011516486a24df1bd2df85441ab17333d3befe685

test:
  secret_key_base: 0cd8132912d719f5289989ead6936d5a596e71d193fce627babb05c58a4b891760cebef357bb1395c4745034d7efba55a8345edbfa6040d4d1ac690a24e47c39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
